### ISSUE TITLE
Template not activated after note creation

### ISSUE THREAD

**Issue by olivr70** [Superschnizel/Obsidian-Moviegrabber#11]
Templater plugin has an option to activate automaticaly on new notes

![image](https://github.com/Superschnizel/Obsidian-Moviegrabber/assets/1276772/64f09bea-8bad-4125-88e8-607134d98af2)

Is does not work with MovieGrabber

For example with this useless example in the MovieGrabber template, it is not replaced after generating a new series
```
<% tp.frontmatter.title %>
```
The real aim is to generate internal links for each genre, for each actor and for the country. From then the Graph View and the Backlinks would be usable with movies.

**Comment by Superschnizel** [comment]
It seems that this happens because Templater is only triggered when a new file is created, but not when an existing note is overwritten. i have changed it so that overwriting a note also triggers the "create" event wich activates templater.

Additionally i have introduced the ability to define a pre- and suffix for the data in the templates, so if you want to create internal links you can now use the pattern `{{Director|"[[|]]"}}` to generate an internal link of the form `"[[Director]]`. If the data is a list, the pre- and suffix will be applied to each individual item.

**Comment by olivr70** [comment]
Amazing and elegant solution for placeholder substitution.

Thanks a lot.
