### ISSUE TITLE
No md-note generated

### ISSUE THREAD

**Issue by connect-m** [Superschnizel/Obsidian-Moviegrabber#5]
I configured the API keys and run the command which successfully show a list of movies to choose from.
Next msg is: 
"Creating note for:<name of movie>". Unfortunately there is no new note inside the Movies folder.

Is there any log that shows the error?

**Comment by connect-m** [comment]
Correction: ""Creating note for:" meant ""Creating note for: (name of movie)".

**Comment by connect-m** [comment]
The console shows here:

app.js:1 Uncaught (in promise) Error: Request failed, status 403
    at new t (app.js:1:1827905)
    at z_ (app.js:1:1828097)
    at app.js:1:1828774
    at app.js:1:237027
    at Object.next (app.js:1:237132)
    at a (app.js:1:235850)

**Comment by Superschnizel** [comment]
okay, it seems that one of the requests failed and this is not accounted for. Since the search works i think this might be the youtube API throwing an error. 

403 means forbidden, wich means that there could be a problem with your API key.

to find out if this is the issue you could use visit this link to see if you can use the API:

```
https://youtube.googleapis.com/youtube/v3/search?part=snippet&q=movietrailer&type=video&key=[YOUR_API_KEY]
```

anyways, i will create an update that handles this kind of case better and also makes the youtube API use optional, so you will be able to use the plugin anyways.

**Comment by connect-m** [comment]
Thanks, that worked.

I had to add a) my credit card for any possible payment on this project and b) enable access to "YouTube Data API v3". After that it runs fine. :)

**Comment by Superschnizel** [comment]
Great that it works now. 
I wonder why you had to enter your credit card, for me the API worked without one. As far as i know the usage of the API is free.

**Comment by connect-m** [comment]
>>As far as i know the usage of the API is free.

I think ie. Maps API isn't free either. I used to setup a valid credit card to use the Maps api. Google changed it some time ago. No big problem since one almost never breaks the pay barrier so that it feels to be free.
